export enum NodeLabel {
  AWS_ACCOUNT = "AWSAccount",
  AWS_RESOURCE = "AWSResource",
  AWS_SERVICE = "AWSService",
  AWS_USER = "AWSUser",
  GLUE_JOB = "GlueJob",
  GLUE_DATABASE = "GlueDatabase",
  GLUE_TABLE = "GlueTable",
  LAMBDA = "Lambda",
  BUCKET = "Bucket",
  ROLE = "Role",
  POLICY = "Policy",
  INLINE_POLICY = "InlinePolicy",
  AWS_MANAGED_POLICY = "AWSManagedPolicy",
  CUSTOMER_MANAGED_POLICY = "CustomerManagedPolicy",
  POLICY_VERSION = "PolicyVersion",
  ATHENA_WORKGROUP = "AthenaWorkgroup",
}
